### ISSUE TITLE
Not scanning APs v 1.7.0

### ISSUE THREAD

**Issue by x0r3n** [aluminum-ice/pwnagotchi#10]
Tried the latest yesterday released 1.7.0 build on my RPI zero 2 W , still not scanning/finding APs :( (same problem was with 1.6.2) 
Do you have any idea what the problem could be ? I have seen similar problems with others, but i can't find a solution anywhere

There are No errors in log.
<img width="1021" alt="image" src="https://github.com/aluminum-ice/pwnagotchi/assets/46898296/75415ce4-557b-4f21-8dad-ffe69cfc3e77">

This is my interface list 
`lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 750  bytes 1275079 (1.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 750  bytes 1275079 (1.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mon0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        unspec E4-5F-01-7E-90-EE-30-30-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

usb0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.2  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::fc51:11ff:fecf:5623  prefixlen 64  scopeid 0x20<link>
        ether fe:51:11:cf:56:23  txqueuelen 1000  (Ethernet)
        RX packets 1129  bytes 128936 (125.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1164  bytes 1002786 (979.2 KiB)
        TX errors 0  dropped 3 overruns 0  carrier 0  collisions 0`

**Comment by naturekid72** [comment]
Same here

**Comment by x0r3n** [comment]
In my case I found the problem.
My raspberry zero 2 W using brcmfmac43430-sdio firmware and not brcmfmac43436-sdio which was patched in this build.
You can see it at boot which firmware is loading for your chip. You can check it with command 
`dmesg | grep brcmf_fw_alloc_request`
in my case:
`[ 6.174867] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1`

**Comment by jayofelony** [comment]
I also have a Pi 0 2W with the Pi3B+ chip.
```
[    9.173508] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    9.260619] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436s-sdio for chip BCM43430/1
[    9.299803] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43436s-sdio.clm_blob failed with error -2
[    9.344957] usbcore: registered new interface driver brcmfmac
[    9.524098] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[    9.525185] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Jul  5 2022 21:29:56 version 7.45.96.141 (g53ba0094) FWID 01-eef9b3bf es7`
```

Tried loading both firmwares for the 43430, both are not being loaded at boot after depmod -a.

**Comment by renewedbullet** [comment]
same issue as above 43430/1
Just got my pi zero 2 w a week ago if that makes any difference.

**Comment by aluminum-ice** [comment]
Try release v1.7.2 that I just published (and if that does not work then v1.7.1). I have multiple RPiZ2W but all of them have the newer wifi chip. I was not even aware there were at least two revisions for the 2W. I am suspicious that during the pandemic they might have gone back to the older wifi chips or maybe even some other unpublished hardware revision when supply chains were gummed up.

**Comment by jayofelony** [comment]
I have one working image for the pi02w, but I think it's an arm (32bit) build. I just flashed it and will see what driver it is using.

Update:
```
dmesg | grep brcm
[   13.773857] brcmfmac: loading out-of-tree module taints kernel.
[   13.822615] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   13.833331] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   13.833621] usbcore: registered new interface driver brcmfmac
[   13.852526] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43430-sdio.raspberrypi,model-zero-2-w.txt failed with error -2
[   14.202403] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   14.202559] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   14.203923] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Aug  7 2017 00:46:29 version 7.45.41.46 (r666254 CY) FWID 01-f8a78378
[   16.800855] brcmfmac: brcmf_vif_add_validate: Attempt to add a MONITOR interface...
[   16.800903] brcmfmac: brcmf_mon_add_vif: brcmf_mon_add_vif called
[   16.800926] brcmfmac: brcmf_mon_add_vif: Adding vif "mon0"
[   16.922911] brcmfmac: brcmf_cfg80211_set_power_mgmt: Forcing power management
[   16.922936] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save disabled
[   16.932566] brcmfmac: brcmf_cfg80211_set_power_mgmt: Forcing power management


uname -r
5.10.63-v7+
```

**Comment by aluminum-ice** [comment]
That RPiZ2W has the older wifi chip. You can see it is using brcmfmac43430-sdio. RPiZ2W with the newer wifi chips would use brcmfmac43436-sdio. All my RPiZ2W have the newer wifi chips, which is likely why I see things working for me but some folks don't.

**Comment by jayofelony** [comment]
Yes but it is the same pi that will not load the drivers on 64 bit raspios. But for some reason it will load this arm build driver.

**Comment by aluminum-ice** [comment]
No idea. I suspect RPi has been playing fast and loose with the hardware for the RPiZ2W. Maybe they're using different wifi chips, which is why its so janky for people. Some are delighted with my folk and others are sad. This is a hobby, so I won't be tracking this down. If you have the same revision of hardware I have, my release 1.7.0 will work well for you. If the community finds a solution, I will merge a pull request.

**Comment by renewedbullet** [comment]
Appreciate the effort ill reuse this zero 2 for some other project

pi@pwnagotchi:~ $ sudo dmesg | grep brcmf_fw_alloc_request
[    6.484808] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    6.868646] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1

**Comment by aluminum-ice** [comment]
@renewedbullet Do you have another RPiZ2w that uses the newer wifi chip? Would be good if you do to get feedback if it works for you.

**Comment by aluminum-ice** [comment]
As a temporary fix for those having trouble getting 1.7.1 to work, please delete these files and reboot your pwnagotchi. For some people with the older wifi chip, this may resolve the firmware crash:

/lib/firmware/brcm/brcmfmac43430-sdio.clm_blob
/lib/firmware/brcm/brcmfmac43430-sdio.raspberrypi,3-model-b.clm_blob

**Comment by x0r3n** [comment]
1.7.3 looks work, finding APs. I will test it longer time now.
I am very grateful for your work! Thank you for your invested time to it.

**Comment by x0r3n** [comment]
> 1.7.3 looks work, finding APs. I will test it longer time now. I am very grateful for your work! Thank you for your invested time to it.

Atm looks good :) Go out a bit, and now scanning is fine )

![IMG_6665](https://github.com/aluminum-ice/pwnagotchi/assets/46898296/daf2ebd8-3b02-40a8-9acb-9e9e9b9fb3ef)
