### ISSUE TITLE
Not booting into AUTO mode [BUG]

### ISSUE THREAD

**Issue by azzarin** [aluminum-ice/pwnagotchi#16]
The pi does not boot to AUTO mode when usb is plugged into power only interface. It only boots to MANU mode. 
I can ssh to the pi and restart into AUTO mode and it works just fine. But i have not set up BT connection, so on the go its not possible. 

**To Reproduce**
1. ... Plug usb to power USB port.

**Expected behavior**
Boot to AUTO mode not MANU. 

**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version V1.7.4
 - OS version
 - Type of hardware Pi zero 2 W
 - Any additional hardware used: Inky screen

**Additional context**

**Comment by Jilten** [comment]
This is happening for me as well :(
Pwnagotchi version V1.7.4
Type of hardware Pi zero 2 W
Any additional hardware used: Waveshare 2

**Comment by glowf1sh** [comment]
i also have the same on 1.7.6. A quick solution for me was to do this:

1) touch /root/.pwnagotchi-auto
2) chattr +i /root/.pwnagotchi-auto
3) reboot

after that it will always reboot in AUTO mode. The 2nd command will prevent the OS to delete the /root/.pwnagotchi-auto file on startup.

**Comment by Coach4** [comment]
I am having this same issue with 1.7.4.  Will this work?  Also is this going into powershell or into the SSH?  Thanks!  Newbie here just looking for some help.   Thanks again!


i also have the same on 1.7.6. A quick solution for me was to do this:

touch /root/.pwnagotchi-auto
chattr +i /root/.pwnagotchi-auto
reboot
after that it will always reboot in AUTO mode. The 2nd command will prevent the OS to delete the /root/.pwnagotchi-auto file on startup.

**Comment by glowf1sh** [comment]
hi @Coach4 - you have to issue these commands when you are connected to the pwnagotchi via SSH. Powershell is only for windows. You have to connect via ssh pi@ip.ip.ip.ip and than you can issue the commands above.

**Comment by Coach4** [comment]
@glowfishDE.  Just wanted to say thanks!  Works absolutely amazing!

**Comment by ZexX-pt** [comment]
Hi too am having the same issue.
The work around provided by @glowfishDE (sorry for my mistake earlier in giving credit to @Coach4 for the fix) fixes for now, but it is not ideal because this forces it to always boot in AUTO mode, even when connecting to the data port.

The original issue described, and the one I also have, is that it always boots in MANU mode, even when using the power port.

**Comment by azzarin** [comment]
> I am having this same issue with 1.7.4. Will this work? Also is this going into powershell or into the SSH? Thanks! Newbie here just looking for some help. Thanks again!
> 
> i also have the same on 1.7.6. A quick solution for me was to do this:
> 
> touch /root/.pwnagotchi-auto chattr +i /root/.pwnagotchi-auto reboot after that it will always reboot in AUTO mode. The 2nd command will prevent the OS to delete the /root/.pwnagotchi-auto file on startup.

This makes perfect sense and is described in the official documentation.

**Comment by glowf1sh** [comment]
> Hi too am having the same issue. The work around provided by @Coach4 fixes for now, 

work around was provided by @glowfishDE ;) just sayin´

**Comment by ZexX-pt** [comment]
> > Hi too am having the same issue. The work around provided by @Coach4 fixes for now,
> 
> work around was provided by @glowfishDE ;) just sayin´

Sorry @glowfishDE ! My mistake

**Comment by NewAbbreviations950** [comment]
pull request submitted fixing this issue #19
