### ISSUE TITLE
[BUG] bettercap web UI is not reachable

### ISSUE THREAD

**Issue by glowf1sh** [aluminum-ice/pwnagotchi#18]
**Describe the bug**
The bettercap web UI is not reachable at the IP port 80

**To Reproduce**
1. enter http://10.0.0.99:80 or http://10.0.0.99 (i have changed my IP for the pwnagotchi to 10.0.0.99 because 10.0.0.2 is already used in my network)

**Expected behavior**
Web Site loads in any browser

**Environment (please complete the following information):**
 - Pwnagotchi version 1.7.6
 - RPI zero 2 W

**Additional context**
Whatever i tried, the webUI for bettercap does not show up. I can access the normal pwnagotchi web ui at http://10.0.0.99:8080 however just fine.

This happens in MANU, AUTO and AI mode. I was never able to reach the Port 80 bettercap WebUI. In config.toml it is configured correctly.

netstat -tulpn also shows that it runs just fine. So i have no idea why it is not accessible.

**Comment by josepgl** [comment]
@glowfishDE Do you see bettercap process running? Have you checked with `ss -ltn` to see if it's there?

**Comment by flexone1** [comment]
i have the same problem on the RPi Zero 1 W.
error log: "[INFO] waiting for bettercap API to be available ..."

`ss -ltn` output:

State          Recv-Q         Send-Q                 Local Address:Port                   Peer Address:Port
LISTEN         0              128                        127.0.0.1:56879                       0.0.0.0:*
LISTEN         0              128                         10.0.0.2:8080                        0.0.0.0:*
LISTEN         0              128                          0.0.0.0:22                          0.0.0.0:*
LISTEN         0              128                          0.0.0.0:1024                        0.0.0.0:*
LISTEN         0              128                          0.0.0.0:38379                       0.0.0.0:*
LISTEN         0              128                             [::]:22                             [::]:*

what can i do?

**Comment by rsun0525** [comment]
I installed 1.7.5 (I don't see a 1.7.6) on a Raspberry Pi Zero 2W (and on a Raspberry Pi 3B+) and I can get to bettercap ui just fine with the username and password defined in the config.toml file, so I cannot reproduce your problem, I would guess you have an issue with your config.toml file

**Comment by dd900** [comment]
Pi Zero 2 W

I'm also having this issue on 1.7.5 and 1.7.6. Getting "connection refused" error in the browser. This is happening with both Bluetooth and PC connection.
