### ISSUE TITLE
[BUG] error while running "plugin".on_ui_update : can't start new thread

### ISSUE THREAD

**Issue by LegendEvent** [aluminum-ice/pwnagotchi#24]
**Describe the bug**
3-4 minutes after Pwnagotchi starts, I get the following error messages for each activated plugin: 
"error while running aircrackonly.on_ui_update : can't start new thread
can't start new thread
Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/__init__.py", line 99, in one
_thread.start_new_thread(locked_cb, locked_cb_args)
RuntimeError: can't start new thread"
**To Reproduce**
1. boot
2. wait
3. error message will appear in pwnagotchi.log

**Expected behavior**
no errors should be seen 
**Screenshots**

**Environment (please complete the following information):**
 - Pwnagotchi version => 1.7.5
 - OS version => Linux 5.10.103-v7+
 - Type of hardware => Raspberry Pi Zero 2 W Rev 1.0
 - Any additional hardware used => waveshare v3 e-ink display

Attached is my config and the pwnaghotchi log
[config.toml.txt](https://github.com/aluminum-ice/pwnagotchi/files/12418171/config.toml.txt)
[pwnagotchi_log.txt](https://github.com/aluminum-ice/pwnagotchi/files/12418168/pwnagotchi_log.txt)

**Comment by aluminum-ice** [comment]
Resolved.
