### ISSUE TITLE
[Feature Request] Display Hat Mini support

### ISSUE THREAD

**Issue by NeonLightning** [aluminum-ice/pwnagotchi#28]
**Is your feature request related to a problem? Please describe.**
Display Hat Mini isn't supported

**Describe the solution you'd like**
include
https://github.com/evilsocket/pwnagotchi/pull/1113

it's only 5 files that don't conflict with your setup :)

**Comment by aluminum-ice** [comment]
I have added it to my pre-release code base for the next release.

**Comment by aluminum-ice** [comment]
[Resolved](https://github.com/aluminum-ice/pwnagotchi/releases/tag/v1.7.6)
