### ISSUE TITLE
[BUG] can't "git pull" the get updates

### ISSUE THREAD

**Issue by naturekid72** [aluminum-ice/pwnagotchi#34]
Can't go to
user/local/etc/pwnagotchi
and do a "git pull"
as with the original evilsocket version.

Or am I just in the wrong dir?

**Comment by aluminum-ice** [comment]
Never tried it tbh so not sure.

**Comment by naturekid72** [comment]
It was always very convenient to update the pwnagotchi.

**Comment by naturekid72** [comment]
How can I update at the moment without having to reflash?
