### ISSUE TITLE
[BUG] No pwnagotchi peering

### ISSUE THREAD

**Issue by waterfallm** [aluminum-ice/pwnagotchi#4]
**Describe the bug**
No pwnagotchi peering since upgrading to 1.6..2

**To Reproduce**
1. start 2nd pownagotchi device up

**Expected behavior**
Peer information displayed

**Environment (please complete the following information):**
 - 1.6.2 x 2
 - PI Zero W 2 off

**Additional context**
Had previously seen peering information running 1.5.5 tried with and without grid enabled.

Note: I also suspect the Wifi card has different setting under this version as the Wifi seems to find less devices.

**Comment by waterfallm** [comment]
Finally got around to testing again with 1.5.5 installed and peering returns

![image](https://user-images.githubusercontent.com/9378879/228293308-f9e388a3-26b0-4047-b5ce-32b5ba7d7d5b.png)

**Comment by RasTacsko** [comment]
I have the same issue.
1.5.1 and 1.5.5 can see each other but cannot see the 1.6.2 version.
1.6.2 version can see both older ones.
So the peer detection is working, but it seems the advertisement part is not.

**Comment by aluminum-ice** [comment]
I don't use this feature. But are you sure the parameters in config.toml are set correctly?

**Comment by RasTacsko** [comment]
Yepp, I used the same config.toml with 1.5.x release and after fresh install the 1.6.2 version almost immediately recognised

**Comment by waterfallm** [comment]
> So the peer detection is working, but it seems the advertisement part is not.

Great i hadn't tried this way around yet i'll introduce a 1.6.2 version into the mix and see what i can see.

**Comment by waterfallm** [comment]
> Great i hadn't tried this way around yet i'll introduce a 1.6.2 version into the mix and see what i can see.

tried with 1.7.0 and 1.6.2

1.7.0 will display in peers tab and also on home screen

1.6.2 doesn't see 1.7.0 peer in either homer or peers tab. BUT 1.6.2 will receive a mseeage from a 1.7.0 client.

**Comment by rsun0525** [comment]
After implementing 1.7.5, the peers are working perfectly for me now, I think you can close this issue.

**Comment by waterfallm** [comment]
Only just seen this.. tested and working fine..
