### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by deadcyborg00** [aluminum-ice/pwnagotchi#52]
Describe the bug
Pwnagotchi does not boot in MANU mode

To Reproduce

Plug the cable in the data port
Wait for the pwnagotchi to boot
pwnagotchi boots into AUTO mode
Expected behavior
pwnagotchi boots into MANU mode

Environment (please complete the following information):

Pwnagotchi version : v1.7.9
OS version : standard raspbian lite image
Type of hardware Raspberry pi 0 2W 
Any additional hardware used waveshare v3 2.13 inch e-paper hat

**Comment by aluminum-ice** [comment]
Did you attempt to figure out why?
