### ISSUE TITLE
[BUG] bettercap https-webui credentials amnesia

### ISSUE THREAD

**Issue by bpinard** [aluminum-ice/pwnagotchi#7]
**Describe the bug**
bettercap occasionally "forgets" login credentials even though they are correctly set in the caplet file https-ui. ssl certs were generated.

**To Reproduce**
1. install 1.6.2
2. configure bettercap caplet https-ui and be sure to change the credentials to something memorable
3. run https-ui caplet in bettercap http ui
4. attempt to login with the credentials via the bettercap https web ui
5. login will fail; I have tried different ports.

**Expected behavior**
Be able to log into the https version of bettercap webui

**Screenshots**
If applicable, add screenshots to help explain your problem.:  n/a, view the web ui and you will see the red message at the top of the interface.  I'm trying to address that. Followed all bettercap instructions so I believe the issue may be an existing bug with pwnagotchi code and how it interfaces with bettercap somehow.

**Environment (please complete the following information):**
 - Pwnagotchi version 1.6.2
 - OS version
 - Type of hardware: Pi zero 2w
 - Any additional hardware used: ds3231 rtc, waveshare v2 display 

**Additional context**
I apologize in advance if my bug report is underwhelming; I'd like to get more involved in the project and have lots of time to test things out currently.

**Comment by aluminum-ice** [comment]
Try v1.7.51 that I will be releasing in a day or two. If I don't hear back, I will assume this is resolved and close the issue.
