### ISSUE TITLE
Support for Waveshare V4

### ISSUE THREAD

**Issue by marvellousmarvolo** [aluminum-ice/pwnagotchi#74]
**Is your feature request related to a problem? Please describe.**
The newest iteration of the Waveshare 2.13 e-ink display is not yet fully supported. The currently available driver for the waveshare213inb_v4 supports the display in part but only features full refresh mode which is impractical.

**Describe the solution you'd like**
Implement a new display based on the official Waveshare driver [available here](https://github.com/waveshareteam/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13_V4.py).

**Describe alternatives you've considered**
N/A

**Additional context**
I have already implemented the change. PR follows shortly.

**Comment by jasonfen** [comment]
will this be integrated into an upcoming img release?

PS thank you :)
