### ISSUE TITLE
v1.8.3 no FAT32 Partition [BUG]

### ISSUE THREAD

**Issue by jasonfen** [aluminum-ice/pwnagotchi#90]
**Describe the bug**
Flashing v1.8.3 to SD card does not create the FAT32 partition for dropping config.toml pre-boot.

**To Reproduce**
1. Download v1.8.3
2. Flash with Balena Etcher
3. Drive shows as single RAW Partition (Windows Disk Manager)

**Expected behavior**
A FAT32 partition is expected on a clean flashed card.

**Screenshots**
![image](https://github.com/aluminum-ice/pwnagotchi/assets/20525926/0a3a7801-06b2-4b35-b59b-465e2260ac40)

**Comment by aluminum-ice** [comment]
Use the Rapsberry PI imager
